"""accommodation

Revision ID: 470723595144
Revises: 1b37463e862f
Create Date: 2022-02-16 12:56:01.178042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470723595144'
down_revision = '1b37463e862f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_accommodation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('chosen_accommodation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('chosen_accommodation_id', 'accommodation', ['chosen_accommodation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint('chosen_accommodation_id', type_='foreignkey')
        batch_op.drop_column('chosen_accommodation_id')
        batch_op.drop_column('needs_accommodation')

    op.drop_table('accommodation')
    # ### end Alembic commands ###
