"""accommodation link

Revision ID: 6e061b87db0b
Revises: 470723595144
Create Date: 2022-02-16 17:51:36.285338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e061b87db0b'
down_revision = '470723595144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
