"""remove unique constr on participant

Revision ID: 8daaf9988cd9
Revises: ecb3520fcdf8
Create Date: 2022-02-11 14:52:25.041289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8daaf9988cd9'
down_revision = 'ecb3520fcdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index('ix_participant_institution')
        batch_op.create_index(batch_op.f('ix_participant_institution'), ['institution'], unique=False)
        batch_op.drop_index('ix_participant_name')
        batch_op.create_index(batch_op.f('ix_participant_name'), ['name'], unique=False)
        batch_op.drop_index('ix_participant_surname')
        batch_op.create_index(batch_op.f('ix_participant_surname'), ['surname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_surname'))
        batch_op.create_index('ix_participant_surname', ['surname'], unique=False)
        batch_op.drop_index(batch_op.f('ix_participant_name'))
        batch_op.create_index('ix_participant_name', ['name'], unique=False)
        batch_op.drop_index(batch_op.f('ix_participant_institution'))
        batch_op.create_index('ix_participant_institution', ['institution'], unique=False)

    # ### end Alembic commands ###
