"""participant reciepts

Revision ID: 8e7a87f3478b
Revises: 8daaf9988cd9
Create Date: 2022-02-14 17:32:51.654263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7a87f3478b'
down_revision = '8daaf9988cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_location', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_participant_receipt_location'), ['receipt_location'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_receipt_location'))
        batch_op.drop_column('receipt_location')

    # ### end Alembic commands ###
